spring:
  datasource:
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: croot
    url: jdbc:mysql://localhost:3306/jxc?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
server:
  port: 8009